- name: Deploy web server for the portfolio site
  hosts: all
  become: yes
  become_user: root

  vars:
    tomcat_version: 8.5.59
    tomcat_version_major: 8

  tasks:
    # Begin
    - name: Echo date
      command: date
      register: date
    - debug: var=date.stdout_lines

    # Java
    - name: Ensure Java is installed
      apt:
        name: default-jdk
        state: present

    # Tomcat user + group
    - name: Ensure tomcat group is created
      group:
        name: tomcat
        state: present

    - name: Ensure tomcat user is created and owner of /opt/tomcat
      user:
        name: tomcat
        group: tomcat
        create_home: yes
        home: /opt/tomcat
        system: yes
        shell: /bin/false

    # Tomcat 8
    - name: Ensure Tomcat directory is created
      file:
        path: /opt/tomcat
        owner: tomcat
        group: tomcat
        state: directory

    - name: Ensure archive is downloaded and extracted
      unarchive:
        src: "http://archive.apache.org/dist/tomcat/tomcat-{{ tomcat_version_major }}/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
        remote_src: yes
        dest: /opt/tomcat
        creates: /opt/tomcat/apache-tomcat-{{ tomcat_version }}
        owner: tomcat
        group: tomcat

    - name: Ensure symlink from latest to extracted directory
      file:
        src: "/opt/tomcat/apache-tomcat-{{ tomcat_version }}"
        dest: /opt/tomcat/latest
        state: link
        owner: tomcat
        group: tomcat

    - name: Ensure Tomcat is registered as a service
      template:
        src: ./resources/tomcat.service.j2
        dest: /etc/systemd/system/tomcat.service

    # Deploy the site
    - name: Ensure WAR file is downloaded and up to date
      synchronize:
        src: ./resources/ROOT.war
        dest: "/opt/tomcat/apache-tomcat-{{ tomcat_version }}/webapps/"

    - name: Restart Tomcat
      systemd:
        name: tomcat
        state: restarted
        enabled: yes

    # Nginx web server
    - name: Ensure Nginx is installed
      apt:
        name: nginx
        state: present

    - name: Ensure default pages are removed
      file:
        path: /var/www/html/index.nginx-debian.html
        state: absent

    - name: Ensure Nginx reverse proxy is configured
      synchronize:
        src: ./resources/davidliao.conf
        dest: /etc/nginx/conf.d/

    - name: Ensure resume HTML is created
      synchronize:
        src: ./resources/resume.html
        dest: /var/www/html/

    - name: Ensure Nginx configuration for resume HTML is created
      synchronize:
        src: ./resources/resume.conf
        dest: /etc/nginx/conf.d/
    
    # - name: Ensure symlink is created from conf-enabled to conf-available
    #   file:
    #     src: /etc/apache2/conf-available/davidliao.conf
    #     dest: /etc/apache2/conf-enabled/davidliao.conf
    #     state: link

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
        enabled: yes
